# Generated by Django 3.2 on 2021-04-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_number', models.CharField(max_length=4, unique=True)),
                ('family', models.CharField(max_length=200)),
                ('url', models.SlugField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('date_from_begin', models.DateField()),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ('-family',),
            },
        ),
        migrations.CreateModel(
            name='Kabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('url', models.SlugField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', models.CharField(max_length=4, unique=True)),
                ('family', models.CharField(max_length=200)),
                ('url', models.SlugField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('adress', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ('-family',),
            },
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_service', models.CharField(max_length=200)),
                ('url', models.SlugField(max_length=200)),
                ('code_service', models.CharField(max_length=4)),
                ('price_service', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_speciality', models.CharField(max_length=200)),
                ('url', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_reception', models.PositiveIntegerField(unique=True)),
                ('url', models.SlugField(max_length=200)),
                ('date_reception', models.DateField()),
                ('time_reception', models.TimeField()),
                ('code_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_services', to='clinic.servicelist')),
                ('number_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_cards', to='clinic.pacient')),
                ('tab_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_numbers', to='clinic.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinic.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='kabinet_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.kabinet'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.speciality'),
        ),
    ]
