# Generated by Django 3.2 on 2021-04-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodoctor',
            name='image',
            field=models.ImageField(null=True, upload_to='clinica/doctors/'),
        ),
    ]
