# Generated by Django 3.2 on 2021-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_photodoctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionpatient',
            name='code_reception',
            field=models.PositiveIntegerField(),
        ),
    ]
