# Generated by Django 3.2 on 2021-04-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_receptionpatient_code_reception'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_reception', models.PositiveIntegerField()),
                ('url', models.SlugField(max_length=200)),
                ('date_reception', models.DateField()),
                ('time_reception', models.TimeField()),
                ('code_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_services', to='clinic.servicelist')),
                ('number_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_cards', to='clinic.pacient')),
                ('tab_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_numbers', to='clinic.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='ReceptionPatient',
        ),
    ]
