# Generated by Django 3.2 on 2021-04-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20210429_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='code_reception',
            field=models.CharField(max_length=200),
        ),
    ]
