# Generated by Django 3.2 on 2021-04-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_reception_code_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='tab_number',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='number_card',
            field=models.CharField(max_length=4),
        ),
    ]
