# Generated by Django 3.2 on 2021-04-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20210429_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='photo',
            field=models.ImageField(null=True, upload_to='pacients/photo/'),
        ),
        migrations.CreateModel(
            name='DocumentPacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='clinica/pacients/documents/')),
                ('image', models.ImageField(null=True, upload_to='clinica/pacients/images/')),
                ('url', models.SlugField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacients', to='clinic.pacient')),
            ],
        ),
    ]
